AllCops:
  Exclude:
    - 'tmp/**/*'

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - 'spec/**/*'
    - 'test/**/*'

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
