services:
  1826:
    Scotland: |
      <p class="govuk-body">We've matched the postcode to <span class="local-authority">%{local_authority_name}</span>.</p>
      <p class="govuk-body">This service is not available in Scotland. You can find other services on the <span class="local-authority">%{local_authority_name}</span> website.</p>
    Northern Ireland: |
      <p class="govuk-body">We've matched the postcode to <span class="local-authority">%{local_authority_name}</span>.</p>
      <p class="govuk-body">This service is not available in Northern Ireland. You can find other services on the <span class="local-authority">%{local_authority_name}</span> website.</p>
